name: Deploy Dist Folder

on: push

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4
        # run: |
        #   # echo "Cloning Repo!"
        #   # git clone https://github.com/${{ github.repository }}.git myfiles
        #   # cd myfiles
        #   # Get-ChildItem
      - name: setup node js
        uses: actions/setup-node@v4
        with: 
          node-version: 22
      - name: print node version
        run: node -v
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test
      - name: Completed Job
        run: echo "Test job was success"


  build:
      runs-on: windows-latest

      steps:
        - name: Get Code
          uses: actions/checkout@v4

        - name: setup node js
          uses: actions/setup-node@v4
          with: 
            node-version: 22
        - name: print node version
          run: node -v
        - name: Install Dependencies
          run: npm install
        - name: Build Project
          run: npm run build
        - name: Completed Job
          run: echo "Test job was success"
           

  



     
        